#!/usr/bin/python

n = int(raw_input())
h = []

for i in range(0,n):
        h.append(int(raw_input()))

count = h[0] + 1

for i in range(len(h)-1):
        if h[i] == h[i+1]:
                count = count + 2
        elif (h[i] > h[i+1]):
                count = count + (h[i] - h[i+1]) + 2
        else:
                count = count + (h[i+1] - h[i]) + 2

print count
