#!/usr/bin/python

x1,y1,x2,y2 = map(int,raw_input().split())

if (x1 != x2) and (y1!=y2):
	if(abs(x1-x2) != abs(y1-y2)):
		print "-1"
	else:
		print "%d %d %d %d" %(x1,y2,x2,y1)
elif (y1==y2):
	print "%d %d %d %d" %(x1,y1 + abs(x1-x2),x2,y2 + abs(x1-x2))
elif (x1 == x2):
	print "%d %d %d %d" %(x1 +  abs(y1-y2),y1,x2 + abs(y1-y2), y2)
else:
	print "-1"
